version: '3'

services:
    mysql-db:
        image: mysql:8.0
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: api
            MYSQL_PASSWORD: 123456Aa@
            MYSQL_ROOT_HOST: '%'